all:
  children:
    k3s_servers:
      hosts:
        k3s-server-01:
          ansible_host: 10.0.20.10
    k3s_agents:
      hosts:
        k3s-agent-01:
          ansible_host: 10.0.20.21
        k3s-agent-02:
          ansible_host: 10.0.20.22
        k3s-agent-03:
          ansible_host: 10.0.20.23
    k3s_cluster:
      children:
        k3s_servers:
        k3s_agents:
    postgres:
      hosts:
        postgres-01:
          ansible_host: 10.0.30.10
    ollama:
      hosts:
        ollama-01:
          ansible_host: 10.0.20.30
    az_dns:
      hosts:
        dns-az-01:
          ansible_host: 10.0.40.53
    az_ingress:
      hosts:
        ingress-east:
          ansible_host: 10.0.40.61
          region: east
          env_lb_ip: 10.0.20.85
          peer_ip: 10.0.40.62
        ingress-central:
          ansible_host: 10.0.40.62
          region: central
          env_lb_ip: 10.0.20.86
          peer_ip: 10.0.40.61
