---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-azure-sync
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "7" # after vault (5) + unsealer (6)
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/azskylab/homelab.git
    targetRevision: main
    path: kubernetes/manifests/vault-azure-sync
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
